- name: reload systemd
  command: systemctl daemon-reload

- name: restart journald
  service: name=systemd-journald state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted
