matomo_user: matomo
matomo_group: matomo
matomo_root: /var/www/matomo

php_fpm_pm_max_children: 10
php_fpm_pm_start_servers: 1
php_fpm_pm_min_spare_servers: 1
php_fpm_pm_max_spare_servers: 3
php_fpm_pm_max_requests: 500
