"""
Django settings for allodepute project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import dj_email_url
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration


BASE_DIR = Path(__file__).absolute().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET", "y&&(+0(3h1^bqq8nbnh4uxv-64=f9ob+!ug8ofi#4(1@$(5c7w"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"


if not DEBUG:
    sentry_sdk.init(
        dsn="https://453a04d3822e40af9cbd2c7ab68013f4@sentry.io/2717092",
        integrations=[DjangoIntegration()],
        send_default_pii=True,
    )


ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost").split(",")

ADMINS = os.environ.get("ADMINS").split(",") if "ADMINS" in os.environ else []

# Application definition

INSTALLED_APPS = [
    "deputes.apps.DeputesConfig",
    "appels.apps.AppelsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "allodepute.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    ["appels.loaders.MarkdownLoader"],
                )
            ]
            if not DEBUG
            else ["appels.loaders.MarkdownLoader"],
        },
    }
]

WSGI_APPLICATION = "allodepute.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="postgis://allodepute:password@localhost/allodepute"
    )
}

# SMTP
email_config = dj_email_url.config(default="smtp://localhost/")
EMAIL_FILE_PATH = email_config["EMAIL_FILE_PATH"]
EMAIL_HOST_USER = email_config["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = email_config["EMAIL_HOST_PASSWORD"]
EMAIL_HOST = email_config["EMAIL_HOST"]
EMAIL_PORT = email_config["EMAIL_PORT"]
EMAIL_BACKEND = email_config["EMAIL_BACKEND"]
EMAIL_USE_TLS = email_config["EMAIL_USE_TLS"]
EMAIL_USE_SSL = email_config["EMAIL_USE_SSL"]

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

# Journalisation
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "main": {
            "level": "DEBUG" if not DEBUG else "INFO",
            "class": "systemd.journal.JournaldLogHandler"
            if not DEBUG
            else "logging.StreamHandler",
        },
        "email": {"level": "ERROR", "class": "django.utils.log.AdminEmailHandler",},
    },
    "loggers": {
        "django.template": {"handlers": ["main"], "level": "INFO", "propagate": False,},
        "django": {"handlers": ["main", "email"], "level": "DEBUG", "propagate": True},
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.environ.get("STATIC_ROOT", BASE_DIR / "static")

STATICFILES_DIRS = [d for d in os.environ.get("STATIC_DIRS", "").split(":") if d]

# Groupes et argumentaires

GROUPES_MAJORITE = ["LaREM", "MODEM", "UDI-AGIR"]
ARGUMENTAIRES = [
    ("Je ne veux pas que le niveau des pensions baisse", "niveau-pensions",),
    ("Je ne veux pas avoir à travailler plus longtemps", "travailler-plus-longtemps",),
    (
        "Les femmes doivent pouvoir être autonomes au moment de la retraite",
        "autonomie-femmes",
    ),
    ("Je suis contre la retraite par capitalisation", "capitalisation",),
    ("Je ne veux pas que cette réforme nous soit imposée", "projet-impose",),
    (
        "Je ne veux pas que les jeunes d'aujourd'hui soient les sacrifié⋅es du système",
        "jeunes-sacrifies",
    ),
]
