- name: Add PHP FPM
  apt:
    name: php-fpm
    state: present

- name: Add PHP extensions
  apt:
    name: "{{ php_extensions }}"
    state: present

- name: Disable default PHP-FPM pool
  command: mv {{ php_conf_directory }}/fpm/pool.d/www.conf {{ php_conf_directory }}/fpm/pool.d/www.disabled
  args:
    creates: "{{ php_conf_directory }}/fpm/pool.d/www.disabled"
  notify: reload php-fpm
  when: not php_keep_default_pool

- name: Copy php.ini
  template:
    src: php.ini.j2
    dest: "{{ php_conf_directory }}/fpm/php.ini"
  notify:
    - reload php-fpm
