- name: Add latest nginx PPA
  apt_repository:
    repo: 'ppa:nginx/stable'
  when: nginx_latest_ppa|bool

- name: Ensure Nginx is installed
  apt: name=nginx state=latest

- name: Ensure Nginx extras are installed
  apt: name=nginx-extras state=latest

- name: Ensure openssl is installed
  apt: name=openssl state=present

- name: Ensure dhparams are present
  copy:
    dest: /etc/nginx/dhparams.pem
    src: dhparams.pem

- name: Ensure nginx is well configured
  template: src=etc/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: Copy helpful util conf includes
  template:
    src: etc/nginx/{{ item }}.j2
    dest: /etc/nginx/{{ item }}
  loop:
    - uwsgi_params
    - proxy_params
    - fastcgi_params
  notify:
    - reload nginx

- name: Ensure includes dir is present
  file:
    path: /etc/nginx/includes
    state: directory

- name: Install letsencrypt includes
  template: src=etc/nginx/includes/letsencrypt.conf.j2 dest=/etc/nginx/includes/letsencrypt.conf
  register: letsencrypt_includes

- name: Ensure default site is not enabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure basic configuration for letsencrypt is present
  copy: src=etc/nginx/sites-available/99-letsencrypt.conf dest=/etc/nginx/sites-available/99-letsencrypt.conf
  register: letsencrypt_conf

- name: Ensure basic configuration for letsencrypt is enabled
  file:
    path: /etc/nginx/sites-enabled/99-letsencrypt.conf
    src: ../sites-available/99-letsencrypt.conf
    state: link

- name: Reload nginx for letsencrypt
  service: name=nginx state=reloaded
  when: letsencrypt_includes.changed or letsencrypt_conf.changed

- name: Copy additional nginx.service configuration
  copy:
    src: etc/systemd/system/nginx.service.d
    dest: /etc/systemd/system/
  notify:
    - reload systemd
    - restart nginx

- name: Ensure nginx is started and enabled
  service: name=nginx enabled=yes state=started

- name: Ensure goaccess is available
  apt: name=goaccess state=latest

- name: Ensure goaccess config file is present
  copy:
    src: etc/goaccess.conf
    dest: /etc/goaccess.conf

- name: Open port 80
  ufw:
    rule: allow
    port: "80"
  when: not cloudflare_protected|bool

- name: Open port 443
  ufw:
    rule: allow
    port: "443"
  when: not cloudflare_protected|bool

- import_tasks: cloudflare.yml
  when: cloudflare_protected|bool
