# Generated by Django 3.0.2 on 2020-02-01 15:08

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circonscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departement",
                    models.CharField(max_length=3, verbose_name="Code du département"),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        verbose_name="Numéro de la circonscription"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodePostal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="Code postal"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="Position approximative",
                    ),
                ),
                (
                    "communes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        size=None,
                        verbose_name="Communes",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="circonscriptions",
            constraint=models.UniqueConstraint(
                fields=("departement", "numero"), name="code_circonscription"
            ),
        ),
    ]
