# Generated by Django 3.0.2 on 2020-02-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deputes", "0003_depute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circonscription", options={"verbose_name": "Circonscription"},
        ),
        migrations.AlterModelOptions(
            name="depute",
            options={"ordering": ("nom", "prenom"), "verbose_name": "Député"},
        ),
        migrations.AlterField(
            model_name="depute",
            name="groupe",
            field=models.CharField(
                choices=[
                    ("LaREM", "Groupe La République en Marche"),
                    ("MODEM", "Mouvement démocrate et apparentés"),
                    (" SOC", "Socialiste et apparentés"),
                    ("LR", "Les Républicains"),
                    ("GDR", "Gauche démocrate et républicaine"),
                    ("LT", "Libertés et Territoires"),
                    ("UDI-AGIR", "UDI, Agir et Indépendants"),
                    ("FI", "La France insoumise"),
                    ("NI", "Non inscrits"),
                ],
                max_length=10,
                verbose_name="Groupe parlementaire",
            ),
        ),
        migrations.AlterField(
            model_name="depute",
            name="prenom",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
    ]
