# Generated by Django 3.0.3 on 2020-02-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deputes", "0004_auto_20200202_0147"),
    ]

    operations = [
        migrations.AddField(
            model_name="depute",
            name="genre",
            field=models.CharField(default="F", max_length=1, verbose_name="Genre"),
        ),
        migrations.AlterField(
            model_name="depute",
            name="groupe",
            field=models.CharField(
                choices=[
                    ("LaREM", "Groupe La République en Marche"),
                    ("MODEM", "Mouvement démocrate et apparentés"),
                    ("SOC", "Socialiste et apparentés"),
                    ("LR", "Les Républicains"),
                    ("GDR", "Gauche démocrate et républicaine"),
                    ("LT", "Libertés et Territoires"),
                    ("UDI-AGIR", "UDI, Agir et Indépendants"),
                    ("FI", "La France insoumise"),
                    ("NI", "Non inscrits"),
                ],
                max_length=10,
                verbose_name="Groupe parlementaire",
            ),
        ),
    ]
