---
app_name: allodepute
app_user: allodepute
db_name: allodepute
app_domain: allodepute.fr
app_repo: git@github.com:aktiur/allodepute.git
app_repo_directory: /srv/allodepute/repo/
app_redirect_domains:
  - www.allodepute.fr
  - staging.allodepute.fr
  - xn--allodput-f1ad.fr  # allodéputé.fr
  - www.xn--allodput-f1ad.fr  # www.allodéputé.fr

# pour msmtp
smtp_domain: "{{ app_domain }}"
smtp_user: apikey
smtp_password: "{{ vaulted_sendgrid_api_key }}"
smtp_host: smtp.sendgrid.net

# Pour nginx/letsencrypt
letsencrypt_domains: "{{ [app_domain] + app_redirect_domains }}"

# virtualenv
virtualenv_python: "/usr/bin/python3.8"
virtualenv_directory: /srv/allodepute/virtualenv
virtualenv_pipfile_directory: "{{ app_repo_directory }}"
virtualenv_packages:
  - python-dotenv[cli]
  - uwsgi

# Paramètres pour Django
django_python: "{{ virtualenv_directory }}/bin/python"
django_app_name: "{{ app_name }}"
django_user: "{{ app_user }}"
django_group: "{{ app_user }}"
django_domain: "{{ app_domain }}"
django_redirect_domains: "{{ app_redirect_domains }}"
django_src_directory: "{{ app_repo_directory }}src/"
django_env:
  DATABASE_URL: "postgis://%2Fvar%2Frun%2Fpostgresql/{{ db_name }}"
  EMAIL_URL: "submission://{{ smtp_user }}:{{ smtp_password }}@{{ smtp_host }}/"
  ADMINS: "Arthur Cheysson <arthur@cheysson.fr>"
  STATIC_DIRS: "/srv/allodepute/repo/static/"
django_secret: "{{ vaulted_django_secret }}"
django_main_package: "allodepute"


# Paramètres pour PostgreSQL
postgresql_version: 12
postgresql_encoding: 'UTF-8'
postgresql_locale: 'fr_FR.UTF-8'
postgresql_ctype: 'fr_FR.UTF-8'
postgresql_ext_install_dev_headers: yes  # pour pouvoir build psycopg2
#postgresql_ext_install_postgis: yes   ## PLANTE ==> installer manuellement
postgresql_ext_postgis_version: "3"
postgresql_service_enabled: true
# user and database parameters
postgresql_databases:
  - name: "{{ db_name }}"
    owner: "{{ app_user }}"
postgresql_database_extensions:
  - db: "{{ db_name }}"
    extensions:
      - postgis
      - unaccent
postgresql_users:
  - name: "{{ app_user }}"
postgresql_user_privileges:
  - name: "{{ app_user }}"
    db: "{{ db_name }}"
    priv: "ALL"
