- name: Provisionne allodéputé
  hosts: allodepute
  tasks:
    - import_role: { name: "common" }
    - import_role: { name: "msmtp" }
    - import_role: { name: "ANXS.postgresql" }
    - name: ensure libsystemd headers are installed
      apt:
        name: libsystemd-dev
        state: latest
    - import_role:
        name: "django"
