- name: Provisionne allodéputé
  hosts: allodepute
  tasks:
    - import_role: { name: "common" }
    - import_role: { name: "msmtp" }
    - import_role: { name: "ANXS.postgresql" }
    - import_role: { name: python3 }

    - import_tasks: app_tasks.yml

    - import_role:
        name: virtualenv
      tags: deploy

    - import_role:
        name: django
      tags: deploy
