- name: ensure additional app packages are present
  apt:
    name:
      - libsystemd-dev
      - npm
    state: latest

- name: clone code for the application
  git:
    repo: "{{ app_repo }}"
    clone: yes
    update: yes
    force: yes
    dest: "{{ app_repo_directory }}"
    version: master
  tags: deploy
  notify:
    - restart django

- name: install javascript dependencies
  npm:
    path: /srv/allodepute/repo/
  tags: deploy

- name: build javascript bundle
  command:
    cmd: npm run build
    chdir: /srv/allodepute/repo/
  tags: deploy
